import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import styled from "styled-components";
import { resetServerContext } from "react-beautiful-dnd";

export default function Home() {
  resetServerContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Drop and drop
        </h1>

        <div className={styles.grid}>

          <NavButton>
            <Link href="/dragndrop">
              <a><h5>Drag n drop {`->`}</h5></a>
            </Link>
          </NavButton>

          <NavButton>
            <Link href="/tree">
              <a><h5>Tree data {`->`}</h5></a>
            </Link>
          </NavButton>

          
        </div>
      </main>
    </div>
  )
}




const NavButton = styled.div`
  border: solid 1px grey;
  border-radius: 1rem;
  padding: 1rem;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 2rem;
  font-size: 10;
  margin-right: 2rem;
`